### ISSUE TITLE
支援 3dsMAX

### ISSUE THREAD

**Issue by noflame** [MoonShineVFX/core#1]
要讓 core 支援 max 

目前知道要修改到讓 core 可以支援的要點有幾個
- 在 setup 加 max 目錄，寫啟動檔( py )
- 在 avalon-core.avalon.max 裡寫入啟動的程式
- pipeline (請參考 maya 區)

**Comment by davidlatwe** [comment]
This issue was moved to MoonShineVFX/reveries-config#1
