### ISSUE TITLE
MoonShine Config

### ISSUE THREAD

**Issue by davidlatwe** [MoonShineVFX/core#2]
### 動機
目前在進入到 Maya 端想要繼續測試整段流程都會卡在需要遵守 Polly Config 的一些 Publish 規則，有點不太方便。

### 目標
確定一下 Config 的規格，然後製作一個最基本的 Config，便於 Publish，也可以當作往後自家 Config 的基礎。

---

> 編輯 Oct, 5, 2017
> 後來覺得要做一個所謂的 Basic Config 好像不太對，Basic 應該是去蕪存菁並且能泛用的東西，然而眼下我也都還不確定我們的需求細節，所以目標應該反過來才對。
>本 issue 標題就更換成 MoonShine Config。

## 新目標
確定 Config 的規格並且記錄於下，以利日後開發夢想專屬的 Config。
對了，像 Mindbender-config 的 config 叫 Polly，那 MoonShine-config 的就先暫訂 **reveries** 歐~

**Comment by davidpower** [comment]
在 avalon 跟各個 host 底下的 pipeline.install() 都會跑 config 的安裝。
一個能夠被 avalon 或 host 安裝的 config ，最基本要有 `install` 跟 `uninstall` 這兩個 function。

* avalon install
`config/__init__.py`

	```python
	import os
	from pyblish import api as pyblish

	# 取得 PUBLISH_PATH : pyblish plugin 的路徑
	PACKAGE_DIR = os.path.dirname(__file__)
	PLUGINS_DIR = os.path.join(PACKAGE_DIR, "plugins")
	PUBLISH_PATH = os.path.join(PLUGINS_DIR, "publish")

	# 註冊 pyblish plugin 的路徑
	def install():
	    print("Registering global plug-ins..")
	    pyblish.register_plugin_path(PUBLISH_PATH)

	# 註銷 pyblish plugin 的路徑
	def uninstall():
	    pyblish.deregister_plugin_path(PUBLISH_PATH)
	```

* host install
`config/host/__init__.py`

	```python
    import os

    from maya import cmds

    from avalon import maya, api as avalon
    from pyblish import api as pyblish

    from . import menu

    PARENT_DIR = os.path.dirname(__file__)
    PACKAGE_DIR = os.path.dirname(PARENT_DIR)
    PLUGINS_DIR = os.path.join(PACKAGE_DIR, "plugins")

    PUBLISH_PATH = os.path.join(PLUGINS_DIR, "maya", "publish")
    LOAD_PATH = os.path.join(PLUGINS_DIR, "maya", "load")
    CREATE_PATH = os.path.join(PLUGINS_DIR, "maya", "create")

    def install():
	    # 註冊針對 Maya publish 的 Pyblish plugin
        pyblish.register_plugin_path(PUBLISH_PATH)

	    # 註冊 Avalon 讀取與創建 asset 的 plugin
        avalon.register_plugin_path(avalon.Loader, LOAD_PATH)
        avalon.register_plugin_path(avalon.Creator, CREATE_PATH)

	    # Avalon 本身就有一個基本選單，這裡可以載入專為 Maya 建立的選單
        menu.install()

        avalon.on("init", on_init)
        avalon.on("new", on_new)
        avalon.on("save", on_save)

    def uninstall():
        pyblish.deregister_plugin_path(PUBLISH_PATH)
        avalon.deregister_plugin_path(avalon.Loader, LOAD_PATH)
        avalon.deregister_plugin_path(avalon.Creator, CREATE_PATH)

        menu.uninstall()
	```

**Comment by davidlatwe** [comment]
# Create Asset - Creator Plugin

這邊講的 Create Asset 是指在 DCC 內工作時，需要在 Publish Asset 之前做好的準備動作 ( 但如果是處理 Load 進來的 Asset，當然就不必 Create )，Maya 這邊的 Create Asset 實作就是產生一個 `objectSet` 來讓 artist 把成果放進去，有點像是貼上標籤或裝進容器的概念。

注意，這邊提的不是專案管理層面的 [Create Asset](http://forums.moonshine-vfx.info/t/topic/98)。

---

### Creator GUI
在 DCC 內，當 artist 要創建 Asset 容器時，這個 Creator GUI 在啟動時會去搜尋 Host Config 裡的 Asset Create plugin。
```
config ( studio global config )
   ├─ maya ( host lib )
   ├─ plugins
   │    ├─ maya ( host config )
   │    │    ├─ create
   .    .    .    ├─ * config_model.py <--- creator plugin
   .    .    .    .
```
我們可以在 DCC 內執行下面的 code 來看看它回傳的內容。
```python
import avalon.api as api
api.discover(api.Creator)
```
接著 GUI 會列出能夠創建的類型，待 artist 選好之後，會接著實作容器出來。
至於實作的方式則定義在一個繼承 `avalon.pipeline.Creator` 的 `host.pipeline.Creator` 裡面，這邊不多說明。

---
### Creator Plugin
一個 creator plugin 的規格大致如下
```python
class CreateMyAsset(maya.Creator):
    """Doc"""
    name = "myAsset"            #必要資訊
    label = "My Asset"          #必要資訊
    family = "config.myasset"   #必要資訊

    def __init__(self, *args, **kwargs):
        super(CreateMyAsset, self).__init__(*args, **kwargs)
        # 收集或更新資訊，非必要
        self.data.update({
            "attr": ""
        })

    def process(self):
        from maya import cmds
        from avalon import maya
        # 做些額外處理，非必要
        pass
```

**Comment by davidlatwe** [comment]
# Load Asset - Loader Plugin

Loader 會載入先前 publish 過的 Asset 進 DCC，所以就比較複雜了一些，需要為每個 Asset 所屬的 family 以及 representation 類型來辨別需要由哪一個 Loader plugin 來處理入境手續。

---

### Loader GUI

![](https://i.imgur.com/iWu4W79.png)

Loader 也是會去搜尋 Loader Plugin，不同的是，前面的 Creator 是一個 Creator Plugin 產生一個與 family 相應的容器，較為單純，Loader 的話，Plugin 搜尋需要過濾的條件除了 family 之外，多了 representation ( 表現形態 )，所以稍微複雜一點。

下面是 Loader GUI 用來篩選 Loader Plugin 的 code
```python
# Loader 過濾條件
families = version["data"]["families"]
representation = document["name"]
# 尋找 Loader Plugin
loader = next(
    Loader for Loader in api.discover(api.Loader)
    if all([
        representation in Loader.representations,
        any(family in families for family in Loader.families)
    ])
)
# 開始辦理入境
host = api.registered_host()
host.load(Loader=loader, representation=_id)
```

**Comment by davidlatwe** [comment]
# Publish Asset - Pyblish

Publish 是最複雜的環節了... Asset Publish 在 **Pyblish** 的框架流程內有四個主要步驟 **CVEI**

| 順序 | 縮寫    | 全稱          | 說明                                    |
| :--: | :-----: | :-----------: | :-------------------------------------- |
| 1    | C       | Collect       | 資訊與 Asset 收集                       |
| 2    | V       | Validate      | 驗證 Asset                              |
| 3    | E       | Extract       | 輸出 Asset 至暫存區 ( staging area )    |
| 4    | I       | Integrate     | 將輸出的 Asset Presentation 送至發布區  |

只有在每個步驟按照順序且都通過之後，才完成整個 Publish。
每個步驟都有各自類型的 Plugin，其中以 Validate 的 plugin 最為麻煩，其次是 Collect。

**Comment by davidlatwe** [comment]
發現驗證可以讓未滿足的條件只回傳警告，太美妙了。
這樣像是沒有 UV 的模型，就還是可以 publish 並且變成提示以及紀錄了。
🎉

**Comment by davidlatwe** [comment]
This issue was moved to MoonShineVFX/reveries-config#2
