### ISSUE TITLE
The relationship between Families and Subset

### ISSUE THREAD

**Issue by davidlatwe** [MoonShineVFX/core#9]
This image was trying to visualize how Avalon process digital content ( subset ), and how plugins interact with `families`, `subset name`, `presentation` these three data.

![](https://i.imgur.com/h4D1YAM.png)

If this describe correctly, I could say :
* Creator define what kind of `subset` this content will be and what `families` it belong.
* During publish, the extractor plugin realize it's `representation`.
* Loader tools list out the subset of the asset we have, than according to `families` and `representation` provide by the subset, loader picks the right plugin to load.

and

* From management point of view, `subset name` is a short term to describe `families`.
* `families` defines how we publish.
* `subset` defines how we integrate to asset chain.

---

<details>
<summary> reference </summary>
延伸閱讀 :

* getavalon/core#278
* getavalon/core#269
* getavalon/core#246
* getavalon/core#194
* http://forums.pyblish.com/t/multiple-families-workflow/205/2
</details>

**Comment by mottosso** [comment]
Hey @davidlatwe, this looks allright to me. And very pretty picture. :) Did you have any questions about any of this?

**Comment by davidlatwe** [comment]
Thanks @mottosso ! I was checking if I am on the right track. :D
If I understand this right, I do have one further issue about the Loader, #11 
maybe this should post to the main thread ?

**Comment by davidlatwe** [comment]
oh, there is one more, not related to above topic. Mindbender's mesh node has an attribute `.mbid`, how dose that id generated? and when to assign it ? I guess this is how you solve the duplicate dag node name ?

**Comment by mottosso** [comment]
The ID is assigned on file-save, via a callback [here](https://github.com/mindbender-studio/config/blob/61de0c7b6e50d38fd1fe470140e463b721165269/polly/maya/__init__.py#L74). This, along with the fact that a scene cannot be published if not saved, ensures that everything published has an ID.

> I guess this is how you solve the issue of duplicated dag node naming and get away with the namespace when matching things like assigning looks shader ?

That's right. It's a persistent name for each node, that survives being copied and imported.

**Comment by davidlatwe** [comment]
Thank you, @mottosso.  :)

**Comment by davidlatwe** [comment]
This is a follow up thinking. ( noting out loud )

A more accurate way to describe **`families`** to me is :
**a list of `job type` for this creation task**.

And for **`subset`** :
**a `data type` of the result of that creation task**.

**Comment by davidlatwe** [comment]
This issue was moved to MoonShineVFX/reveries-config#9
